# version: "3.8"

services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb_container"
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartprep
      MONGO_INITDB_ROOT_PASSWORD: smartprep
      MONGO_INITDB_DATABASE: smartprep_db
    ports:
      - "27018:27017"
    volumes:
      - mongodbdata:/data/db
    restart: always
    networks:
      - app-network

  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
      - webrtc
    environment:
      - mongodb_url=mongodb://smartprep:smartprep@mongodb:27017
      - DATABASE_NAME=smartprep_db
    volumes:
      - ./uploads:/api/uploads
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000
    networks:
      - app-network

  webrtc:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend/webrtc:/app
    command: "node signalling_server.js"
    ports:
      - "8181:8181"
    networks:
      - app-network

  frontend:
    env_file:
      - frontend/.env.docker
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    depends_on:
      - backend
      - webrtc
    restart: always
    ports:
      - "3006:3006"
    expose:
      - 3006
    networks:
      - app-network

volumes:
  mongodbdata:
    driver: local

networks:
  app-network:
    driver: bridge
