

services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb_container"
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartprep
      MONGO_INITDB_ROOT_PASSWORD: smartprep
    ports:
      - 27018:27017
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:
    driver: local
